@startuml sequenceDiagram_Supplier_getData
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
activate User
User -> View : Click search
activate View
View -> APIService : getSupplier()
deactivate View
activate APIService
note right of APIService: Fetch data from database
APIService -> DB : getSupplier()
deactivate APIService
activate DB
note right of DB: Run Query\nin database
DB --> APIService : Return data
deactivate DB
activate APIService
APIService --> View --++: Display data
deactivate User
deactivate APIService
@enduml
