@startuml sequenceDiagram_Salary_getData
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
User -> View --++ : Choose date and click search
View -> APIService --++ : getSalary(date)
note right of APIService: Fetch data from database\nbased on the selected date
APIService -> DB --++ : getSalary(date)
note right of APIService: Run Query\nin database
DB --> APIService --++ : Return data
APIService --> View : Display data
@enduml