@startuml SequenceDiagram_Login
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
User -> View --++ : Enter username and password
note right of View: Check username and password via api
View -> APIService --++ : Login(username, password)
note right of APIService: Check username and password\nin database
APIService -> DB --++ : Login()
DB --> APIService --++ : Return login result
APIService --> APIService: Check login result
alt #LightGreen Success
    APIService --> View: Display Dashboard
else #Pink Failure
    APIService --> View: Show Alert
end

group Logout
    User -> View --++ : Click logout button
    View -> APIService --++ : Logout()
    APIService -> DB --++ : Invalidate session
    DB --> APIService --++ : Session invalidated
    APIService --> View: Logout successful
end
@enduml