@startuml SequenceDiagram_Login
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
activate User
User -> View : Enter username and password
activate View
note right of View: Check username and password via api
View -> APIService : Login(username, password)
deactivate View
activate APIService
note right of APIService: Check username and password\nin database
APIService -> DB : Login()
deactivate APIService
activate DB
DB --> APIService : Return login result
deactivate DB
activate APIService
APIService --> APIService: Check login result
alt #LightGreen Success
    APIService --> View: Display Dashboard
else #Pink Failure
    APIService --> View: Show Alert
end
deactivate APIService

group Logout
    User -> View : Click logout button
    activate View
    View -> APIService : Logout()
    deactivate View
    activate APIService
    APIService -> DB : Invalidate session
    deactivate APIService
    activate DB
    DB --> APIService : Session invalidated
    deactivate DB
    activate APIService
    APIService --> View --++: Logout successful
    deactivate APIService
end
deactivate User
@enduml
