@startuml sequenceDiagram_Employee_getData
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
User -> View --++ : Click search
View -> APIService --++ : getEmployee()
note right of APIService: Fetch data from database
APIService -> DB --++ : getEmployee()
note right of APIService: Run Query \n in database
DB --> APIService --++ : Return data
APIService --> View : Display data
@enduml