@startuml sequenceDiagram_Product_update
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
activate User
User -> View : Choose data and change data in the form
activate View
View -> APIService : UpdateProduct()
deactivate View
activate APIService
note right of APIService: Send data
APIService -> DB : UpdateProduct()
deactivate APIService
activate DB
note right of DB: Run Query\nin database
DB --> APIService : Return status query
deactivate DB
activate APIService
alt #LightGreen Success
    APIService --> View : Return message success
else #Pink Failure
    APIService --> View : Return message failure
end
deactivate User
deactivate APIService
@enduml
