@startuml sequenceDiagram_Product_getData
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
activate User
User -> View : Click search
activate View
View -> APIService : getProduct()
deactivate View
activate APIService
note right of APIService: Fetch data from database
APIService -> DB : getProduct()
deactivate APIService
activate DB
note right of DB: Run Query \n in database
DB --> APIService : Return data
deactivate DB
activate APIService
APIService --> View --++: Display data
deactivate APIService
deactivate User
@enduml
