@startuml sequenceDiagram_Employee_update
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
User -> View --++ : choose data and  change data in the form
View -> APIService --++ : UpdateEmployee()
note right of APIService: Send data 
APIService -> DB --++ : UpdateEmployee()
note right of APIService: Run Query\nin database
DB --> APIService --++ : Return status query
alt #LightGreen  Success
    APIService --> View  : Return message success
else #Pink Failure
    APIService --> View  : Return message failure
end
@enduml