@startuml sequenceDiagram_Sale
actor User
boundary "View" as View
control "API Service" as APIService
database "My Sql" as DB

autonumber
activate User
User -> View : Choose Product,\nfill in quantity\nand click save
activate View
note right of View: Validate data\nand check if product\nis available in stock
View -> APIService : Sale()
deactivate View
activate APIService
note right of APIService: Send data
APIService -> DB : Sale()
deactivate APIService
activate DB
note right of DB: Run Query\nin database
DB --> APIService : Return status query
deactivate DB
activate APIService
alt #LightGreen Success
    APIService --> View : Return message success
else #Pink Failure
    APIService --> View : Return message failure
end
deactivate User
deactivate APIService
@enduml
